ENTRY = NAME, PHONES, ADRESSES;
NAME = FIRSTNAME , LASTNAME;
FIRSTNAME = FIRSTNAMESTARTTAG, CONTENT, FIRSTNAMEENDTAG;
FIRSTNAMESTARTTAG = TAGSTART, "NAME", TAGEND;
FIRSTNAMEENDTAG = TAGSTART, TAGENDSYMBOL, "NAME", TAGEND;
LASTNAME = LASTNAMESTARTTAG, CONTENT, LASTNAMEENDTAG;
LASTNAMESTARTTAG = TAGSTART, "NACHNAME", TAGEND;
LASTNAMEENDTAG = TAGSTART, TAGENDSYMBOL, "NACHNAME", TAGEND;
PHONES = {PHONE};
PHONE = PHONESTARTTAG, CONTENT, PHONEENDTAG;
PHONESTARTTAG = TAGSTART, "TELEFON", PHONEATTRIBUTES, TAGEND;
PHONEENDTAG = TAGSTART, TAGENDSYMBOL, "TELEFON", TAGEND;
PHONEATTRIBUTES = LANDLINEATTRIBUTES | MOBILEATTRIBUTES;
LANDLINEATTRIBUTES = "typ","=",'"',"festnetz",'"',"land","=", '"',COUNTRY,'"',"stadt","=",'"',CITY,'"';
MOBILEATTRIBUTES = "typ","=",'"',"mobil",'"',"land","=", '"',COUNTRY,'"';
COUNTRY = "Deutschland" | "Kroatien" | "Serbien" | "Bulgarien";
CITY = "München" | "Klenovšćak" | "Belgrad" | "Sofia";
ADRESSES = {ADRESS};
ADRESS = ADRESSTARTTAG, [ DESCRIPTION ] , STREET, ZIPCODE, CITYLINE, COUNTRYLINE, ADRESSENDTAG;
ADRESSTARTTAG= TAGSTART, "ADRESSE", TAGEND;
ADRESSENDTAG=TAGSTART, TAGENDSYMBOL, "ADRESSE", TAGEND;
DESCRIPTION = DESCRIPTIONSTARTTAG, CONTENT, DESCRIPTIONENDTAG;
DESCRIPTIONSTARTTAG = TAGSTART, "BESCHREIBUNG", TAGEND;
DESCRIPTIONENDTAG = TAGSTART, TAGENDSYMBOL, "BESCHREIBUNG", TAGEND;
STREET = STREETSTARTTAG, CONTENT, STREETENDTAG;
STREETSTARTTAG = TAGSTART, "STRASSE", TAGEND;
STREETENDTAG = TAGSTART, TAGENDSYMBOL, "STRASSE", TAGEND;
ZIPCODE = ZIPSTARTTAG, CONTENT, ZIPENDTAG; 
ZIPSTARTTAG = TAGSTART, "PLZ", TAGEND;
ZIPENDTAG = TAGSTART, TAGENDSYMBOL, "PLZ", TAGEND;
CITYLINE = CITYSTARTTAG, CONTENT, CITYENDTAG;
CITYSTARTTAG = TAGSTART, "STADT", TAGEND;
CITYENDTAG = TAGSTART, TAGENDSYMBOL, "STADT", TAGEND;
COUNTRYLINE = COUNTRYSTARTTAG, CONTENT, COUNTRYENDTAG;
COUNTRYSTARTTAG = TAGSTART, "LAND", TAGEND;
COUNTRYENDTAG = TAGSTART, TAGENDSYMBOL, "LAND", TAGEND;
TAGSTART = '<';
TAGENDSYMBOL = '/';
TAGEND = '>';
CONTENT = LETTER,{LETTER-TAGSTART};
LETTER = ?BASIC_LATIN?;
