ENTRY = NAME, PHONES, ADRESSES;
NAME = FIRSTNAME , LASTNAME;
FIRSTNAME = FIRSTNAMESTARTTAG, CONTENT, FIRSTNAMEENDTAG;
FIRSTNAMESTARTTAG = TAGSTART, "NAME", TAGEND;
FIRSTNAMEENDTAG = TAGSTART, TAGENDSYMBOL, "NAME", TAGEND;
LASTNAME = LASTNAMESTARTTAG, CONTENT, LASTNAMEENDTAG;
LASTNAMESTARTTAG = TAGSTART, "NACHNAME", TAGEND;
LASTNAMEENDTAG = TAGSTART, TAGENDSYMBOL, "NACHNAME", TAGEND;
PHONES = {PHONE};
PHONE = PHONESTARTTAG, CONTENT, PHONEENDTAG;
PHONESTARTTAG = TAGSTART, "PHONE", PHONEATTRIBUTES, TAGEND;
PHONEENDTAG = TAGSTART, TAGENDSYMBOL, "PHONE", TAGEND;
PHONEATTRIBUTES = LANDLINEATTRIBUTES | MOBILEATTRIBUTES;
LANDLINEATTRIBUTES = "typ","=",'"',"landline",'"',"country","=", '"',COUNTRY,'"',"city","=",'"',CITY,'"';
MOBILEATTRIBUTES = "typ","=",'"',"mobil",'"',"country","=", '"',COUNTRY,'"';
COUNTRY = "Germany" | "United Kingdom" | "France";
CITY = "London" | "Berlin" | "Paris";
ADRESSES = {ADDRESS};
ADDRESS = ADRESSTARTTAG, [ DESCRIPTION ] , STREET, ZIPCODE, CITYLINE, COUNTRYLINE, ADRESSENDTAG;
ADRESSTARTTAG = TAGSTART, "ADDRESS", TAGEND;
ADRESSENDTAG = TAGSTART, TAGENDSYMBOL, "ADDRESS", TAGEND;
DESCRIPTION = DESCRIPTIONSTARTTAG, CONTENT, DESCRIPTIONENDTAG;
DESCRIPTIONSTARTTAG = TAGSTART, "DESCRIPTION", TAGEND;
DESCRIPTIONENDTAG = TAGSTART, TAGENDSYMBOL, "DESCRIPTION", TAGEND;
STREET = STREETSTARTTAG, CONTENT, STREETENDTAG;
STREETSTARTTAG = TAGSTART, "STREET", TAGEND;
STREETENDTAG = TAGSTART, TAGENDSYMBOL, "STREET", TAGEND;
ZIPCODE = ZIPSTARTTAG, CONTENT, ZIPENDTAG; 
ZIPSTARTTAG = TAGSTART, "ZIP_CODE", TAGEND;
ZIPENDTAG = TAGSTART, TAGENDSYMBOL, "ZIP_CODE", TAGEND;
CITYLINE = CITYSTARTTAG, CONTENT, CITYENDTAG;
CITYSTARTTAG = TAGSTART, "CITY", TAGEND;
CITYENDTAG = TAGSTART, TAGENDSYMBOL, "CITY", TAGEND;
COUNTRYLINE = COUNTRYSTARTTAG, CONTENT, COUNTRYENDTAG;
COUNTRYSTARTTAG = TAGSTART, "COUNTRY", TAGEND;
COUNTRYENDTAG = TAGSTART, TAGENDSYMBOL, "COUNTRY", TAGEND;
TAGSTART = '<';
TAGENDSYMBOL = '/';
TAGEND = '>';
CONTENT = LETTER,{LETTER-TAGSTART};
LETTER = ?BASIC_LATIN?;