OUTPUT = {KENNZEICHEN | NICHT_KENNZEICHEN};
KENNZEICHEN = STADT_KUERZEL, "-", ERKENNUNGS_NUMMER, ZAHLEN;
NICHT_KENNZEICHEN = ?BMP? - KENNZEICHEN;
STADT_KUERZEL = BUCHSTABE, 2*[BUCHSTABE];
ERKENNUNGS_NUMMER = BUCHSTABE, 2*[BUCHSTABE];
BUCHSTABE = ?GERMAN_CAPITALS?;
ZAHLEN = ZAHL, 3*[ZAHL];
ZAHL = ?DIGIT?;