STAGES = {:?BMP?: STAGE };
STAGE = STAGE_LITERAL, STAGE_NAME, OPENING_BRACE, STAGE_CONTENT, CLOSING_BRACE;
STAGE_LITERAL = 'stage';
STAGE_NAME = '(',"'",LETTERS_AND_SPACES,"'",')';
LETTERS_AND_SPACES = { ?LETTER? | ?WHITESPACE? };
OPENING_BRACE = '{';
STAGE_CONTENT = STEPS;
STEPS = STEPS_LITERAL, OPENING_BRACE, STEPS_CONTENT, CLOSING_BRACE;
STEPS_LITERAL = 'steps';
STEPS_CONTENT = 'prepareBuild()' | 'buildJava()' | 'sonarAnalysis()';
CLOSING_BRACE = '}';